# Generated by Django 3.0.6 on 2020-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vpa',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
