# Generated by Django 3.0.6 on 2020-08-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transition',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
